import os
import joblib
import streamlit as st
import pandas as pd

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------
st.set_page_config(
    page_title="Insurance Fraud Detection",
    page_icon="🛡️",
    layout="centered"
)

st.title("🛡️ Insurance Fraud Detection System")
st.write(
    "This application predicts whether an insurance claim is "
    "**fraudulent or genuine** using a trained machine learning pipeline."
)

# --------------------------------------------------
# LOAD MODEL (PIPELINE)
# --------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(BASE_DIR, "best_fraud_pipeline.pkl")

@st.cache_resource
def load_model():
    if not os.path.exists(MODEL_PATH):
        st.error(f"❌ Model file not found at: {MODEL_PATH}")
        st.stop()
    return joblib.load(MODEL_PATH)

model = load_model()
st.success("✅ Model loaded successfully")

# --------------------------------------------------
# USER INPUTS
# --------------------------------------------------
st.subheader("📋 Claim Details")

insurance_type = st.selectbox(
    "Insurance Type",
    ["Life", "Health", "Vehicle", "Travel", "Property"]
)

policy_type = st.selectbox(
    "Policy Type",
    ["Basic", "Standard", "Premium"]
)

incident_type = st.selectbox(
    "Incident Type",
    ["Accident", "Theft", "Medical Claim", "Death Claim", "Fire"]
)

payment_method = st.selectbox(
    "Payment Method",
    ["Bank Transfer", "Cheque", "Cash", "UPI"]
)

region = st.selectbox(
    "Region",
    ["Urban", "Rural", "Semi-Urban"]
)

claim_amount = st.number_input(
    "Claim Amount",
    min_value=1000,
    step=500,
    value=50000
)

# --------------------------------------------------
# ADDITIONAL FEATURES (REQUIRED BY MODEL)
# --------------------------------------------------
st.subheader("📊 Customer & Policy Information")

customer_age = st.number_input(
    "Customer Age",
    min_value=18,
    max_value=100,
    value=35
)

num_previous_claims = st.number_input(
    "Number of Previous Claims",
    min_value=0,
    max_value=20,
    value=0
)

days_since_last_claim = st.number_input(
    "Days Since Last Claim",
    min_value=0,
    value=365
)

policy_tenure_days = st.number_input(
    "Policy Tenure (days)",
    min_value=1,
    value=730
)

claim_processing_days = st.number_input(
    "Claim Processing Days",
    min_value=1,
    value=15
)

# --------------------------------------------------
# PREDICTION
# --------------------------------------------------
if st.button("🔍 Predict Fraud"):
    input_df = pd.DataFrame([{
        "insurance_type": insurance_type,
        "policy_type": policy_type,
        "incident_type": incident_type,
        "payment_method": payment_method,
        "region": region,
        "claim_amount": claim_amount,
        "customer_age": customer_age,
        "num_previous_claims": num_previous_claims,
        "days_since_last_claim": days_since_last_claim,
        "policy_tenure_days": policy_tenure_days,
        "claim_processing_days": claim_processing_days
    }])

    prediction = model.predict(input_df)[0]
    probability = model.predict_proba(input_df)[0][1] * 100

    st.subheader("📊 Prediction Result")

    if prediction == 1:
        st.error("🚨 Fraudulent Claim Detected")
        st.write(f"**Fraud Probability:** {probability:.2f}%")
    else:
        st.success("✅ Genuine Claim")
        st.write(f"**Genuine Probability:** {100 - probability:.2f}%")

# --------------------------------------------------
# DISCLAIMER
# --------------------------------------------------
st.markdown("---")
st.info(
    "⚠️ This prediction is generated by a machine learning model and "
    "should be used for decision support only."
)
